// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqLOb32fLh3m8HA9uxPLIvDft0AtmlQaM',
    appId: '1:49407447823:web:c0a15792bbdf5dc0df647a',
    messagingSenderId: '49407447823',
    projectId: 'caputralens',
    authDomain: 'caputralens.firebaseapp.com',
    storageBucket: 'caputralens.appspot.com',
    measurementId: 'G-8Z5D7PEVEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu7oKMoeAtfPv3eus7JUovvoc7cpvO9KQ',
    appId: '1:49407447823:android:ec65d7d31d281982df647a',
    messagingSenderId: '49407447823',
    projectId: 'caputralens',
    storageBucket: 'caputralens.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvspEDEWWG6XVVGwDknuajtkN9aVb5Z1I',
    appId: '1:49407447823:ios:4916ab5a91e821f9df647a',
    messagingSenderId: '49407447823',
    projectId: 'caputralens',
    storageBucket: 'caputralens.appspot.com',
    iosBundleId: 'com.example.caputralens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvspEDEWWG6XVVGwDknuajtkN9aVb5Z1I',
    appId: '1:49407447823:ios:567911fef78dfe12df647a',
    messagingSenderId: '49407447823',
    projectId: 'caputralens',
    storageBucket: 'caputralens.appspot.com',
    iosBundleId: 'com.example.caputralens.RunnerTests',
  );
}
